import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./providers";
import NavBar from "../components/NavBar";
import Sidebar from "../components/SideBar";

// Fonts setup
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Server-side metadata
export const metadata: Metadata = {
  title: "Demo Ecommerce App",
  description: "Generated by Demo Ecommerce App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-2 p-2`}
      >
        <div className="flex">
          <Sidebar />
          <div className="flex-1 p-4">
            <Providers>
              <NavBar />
              {children}
            </Providers>{" "}
          </div>
        </div>
      </body>
    </html>
  );
}
